# Generated by Django 4.0.3 on 2022-03-15 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManyActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('date_of_birth', models.DateField()),
            ],
            options={
                'db_table': 'manyactors',
            },
        ),
        migrations.CreateModel(
            name='ManyMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('release_date', models.DateField()),
                ('running_time', models.IntegerField()),
            ],
            options={
                'db_table': 'manymovies',
            },
        ),
        migrations.CreateModel(
            name='ManyActor_Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manytomany.manyactor')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manytomany.manymovie')),
            ],
            options={
                'db_table': 'manyactors_movies',
            },
        ),
        migrations.AddField(
            model_name='manyactor',
            name='join',
            field=models.ManyToManyField(related_name='actor', through='manytomany.ManyActor_Movie', to='manytomany.manymovie'),
        ),
    ]
