# Generated by Django 4.0.3 on 2022-03-15 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manytomany', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manyactor',
            old_name='join',
            new_name='jointt',
        ),
    ]
